### ISSUE TITLE
(possibly related to dldr.exe) 16 bit drivers not working

### ISSUE THREAD

**Issue by lza78** [leecher1337/ntvdmx64#189] opened 2022-05-07 13:19 UTC
Hi,
I am trying to install drivers for CanoScan D646U ex (it is a very very old scanner that requires 16 bit) :
the toolbox (this works well with no issue) :  https://www.canon.co.uk/support/consumer_products/products/scanners/canoscan_series/canoscan_d646u.html?type=drivers&driverdetailid=tcm:14-748616&os=windows%20xp%20%2832-bit%29&language=en
and
the driver(the issue) : https://www.canon.co.uk/support/consumer_products/products/scanners/canoscan_series/canoscan_d646uex.html?type=drivers&driverdetailid=tcm:14-750934&os=windows%20xp%20%2832-bit%29&language=en
I didn't put "dldr.exe" as stated in the instruction as I can't find it. So is it related to it that cause the driver can't be installed successfully? The driver is a extractor that will extract some files into your computer and you need to navigate to some .exe to make it run and it will again extract the drivers into another folder. After that, I will copy that path and paste it in Device Manager to make the driver work but it seems that it can't install successfully, stating that there are no drivers at all. Any ideas? Thanks. 
My current OS is Windows 8.1 pro 64bit.

*Btw opennt.net(MinNT-numbers...) seems to be taken down and the same goes to old-src.trunk and also stephanos's NTOSBE. Microsoft is getting quite busy hmmm. Luckily there is something called wayback machine and I saved those files in my onedrive several months ago as well LOL

**Comment by leecher1337** [comment] 2022-05-07 18:01
So you re trying to install a scanner driver for a scanner that isn't compatible with your system? I don't see how this is supposed to work. 

Use Hamrick VueScan, if you want to get an old scanner working on a new Windows machine.

opennt.net wasn't taken down, just the DNS wasn't renewed, see: https://github.com/leecher1337/ntvdmx64/issues/163#issuecomment-1008472401

As the issue is completely unrelated to NTVDMx64, I'll close this now.

**Closed by leecher1337** 2022-05-07 18:01 UTC
