### ISSUE TITLE
My Issues with a fresh compile

### ISSUE THREAD

**Issue by Danfun64** [leecher1337/ntvdmx64#18] opened 2018-01-16 01:00 UTC
I managed to set up the oldnt src and sdk, "SUBST W: ." and get Patch.cmd working, but when I run zSHtst.cmd (which calls sizzletst.cmd; then ntenv.cmd; then finally, and most importantly, ntuser.cmd) it uses an "alias" command, which the command prompt doesn't see as valid. Thusly, attempting to use bld-ntos.cmd , I get "You must set up the Razzle build environment prior to executing this command.
Supported build configurations: *fre, *tst, *chk" 

I can see that it's not going to work without Alias working.

http://paste.debian.net/hidden/b2557f78/

**Comment by leecher1337** [comment] 2018-01-16 13:36
Hi,
Quoting readme.txt from old-src.trunk.r687.20150728.7z 

> Copy alias.exe in tools\(HOSTARCH)\idw directory to your local system32 directory.
> 
> e.g. If your host machine is x86, copy tools\i386\idw\alias.exe to %SystemRoot%\system32.

**Comment by leecher1337** [comment] 2018-01-16 20:54
After looking at the script output, it seems that you are not compiling under Windows XP x86.
The build process has only been tested on Windows XP so far.
The problem is that your architecture is AMD64 and there is no case for this ar chitecture in the Microsoft build scripts (didn't even exist back in NT4 days).
So for me the line
```
if "x86" == "x86" set USERNAME=x86tst
```
evaluates nicely, because I'm on x86 Windows XP and therefore have another control flow.
So better try to compile it on an x86 machine or you may need to modifiy the build scripts according to your needs.
If you just want to try it out in compiled form, see #7

**Comment by Danfun64** [comment] 2018-01-16 21:53
Thanks for the link...but I prefer fresh binaries from the latest commits.

Should I close this issue, or leave it open for potention amd64 porting?

**Comment by leecher1337** [comment] 2018-01-16 22:44
It seems emendelson normally is pretty fast with updating the build. My latest commits are important mainly if you want to debug NTVDM (which is i.e. important to find out if there maybe is a way to get WOW working, but most of the 16bit scheduling currently is done in the kernel, so this may get complicated as NTVDM on x64 is already a WOW32 process and Win 10 x64 is even missing the WOW16 functions in its scheduler, Win 7 x64 still has the functions at least).

**Comment by Danfun64** [comment] 2018-01-17 05:10
Heh, I started over with a 32-bit Windows XP VM, and it actually did something. However, several programs failed to compile when doing bld-ntos.cmd . I plan on starting over so that I could log everything in its entirety.

**Comment by Danfun64** [comment] 2018-01-18 04:06
I'm having trouble finding a way to get the batch and cmd files to log everything. All I can say is that ntvdm.exe does not compile, and I've gotten errors at various places

**Comment by leecher1337** [comment] 2018-01-20 15:10
Hi,
My apologies, I forgot to add a few lines of code to the patches leading to a "getenv" not resolved error, but I now fixed this.
I verified build process and it worked flawlessly. I made a video recording from it which I can provide if it helps.

**Comment by sumitparihar93** [comment] 2019-12-15 08:53
leecher1337 sir can you provide me compiled version of ntvdmx64 on mail.

**Comment by emendelson** [comment] 2019-12-16 01:14
sumitparihar93 see the download page linked from:

https://github.com/leecher1337/ntvdmx64/issues/7

**Closed** 2020-02-28 22:23 UTC
