### ISSUE TITLE
Fortran Error Under Win7x64 With NTVDMx64

### ISSUE THREAD

**Issue by joeyc10** [leecher1337/ntvdmx64#223] opened 2023-04-10 19:40 UTC
I have installed NTVDMx64 CCPU in my Windowsx64 O/S.
All of my 16 bit binaries now run, as well as the MASM and LINK programs.
But the Microsoft Fortran 4.0 program produces the following error --

[
E:\DECBAL>FL /FPi /c /Fs DECBAL.FOR
Microsoft (R) FORTRAN Optimizing Compiler Version 4.00
Copyright (c) Microsoft Corp 1987. All rights reserved.

DECBAL.FOR
fatal error C1042: cannot open compiler intermediate file - no such file or directory

error 2001: Null pointer assignment
fatal error F1042: cannot open compiler intermediate file - no such file or directory
]

I have set up PATH, TMP, and LIB in the Environment Variables pointing to the FORTRAN folder as I have in Windowsx86 where every 16 bit program and binary runs.
Any ideas?

**Comment by leecher1337** [comment] 2023-04-11 14:45
Hm, I cannot reproduce the problem. I installed [FORTRAN 4.10](https://winworldpc.com/download/4863c2bf-c2a5-18c3-9a11-c3a4e284a2ef) via SETUP.EXE and compiled a demo program (DEMO.FOR) just with `FL DEMO.FOR` and it compiled without any issues on Windows 7 x64 using NTVDMx64.
Also set up TMP so point to C:\FORTRAN, my FORTRAN installation directory.

```
c:\FORTRAN>fl DEMOS\DEMO.FOR
Microsoft (R) FORTRAN Optimizing Compiler Version 4.10
Copyright (c) Microsoft Corp 1987, 1988. All rights reserved.

DEMOS\DEMO.FOR

Microsoft (R) Segmented-Executable Linker  Version 5.01.20
Copyright (C) Microsoft Corp 1984-1988.  All rights reserved.

Object Modules [.OBJ]: DEMO.OBJ
Run File [DEMO.EXE]: DEMO.EXE
List File [NUL.MAP]: NUL
Libraries [.LIB]:
Definitions File [NUL.DEF]: ;
```

Created DEMO.EXE also runs fine.

**Comment by joeyc10** [comment] 2023-04-11 19:53
Thanks for your reply. Did you install Fortran while under MS DOS or Windows? The same batch program compiles under Windows7x86 and I can't see what is missing.

**Comment by leecher1337** [comment] 2023-04-11 20:24
I installed with NTVDMx64 under Windows.
Unpacked all installation disks, `subst A: .`, ran installer from A: and pointed all dst. directories to c:\FORTRAN and then let it build the library and stuff. Then made an env.bat that sets up environment variables before build and ran fl command, that's it.

**Comment by leecher1337** [comment] 2024-11-02 22:48
No reply received within 1,5 years, closing

**Closed by leecher1337** 2024-11-02 22:48 UTC
