### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by thed3ct** [leecher1337/ntvdmx64#25] opened 2018-05-22 22:10 UTC
I was using this compiled version of NTVDMX64 [http://www.columbia.edu/~em36/ntvdmx64.html](url)
For some time it was working fine, but recently it just stopped working. When I'm trying to run
any 16-bit application then it shows me an error message saying that "This app can't be run on your pc".

I even tryed to reinstall NTVDMx64, but it didn't help...

(im using Windows 8.1 x64)

**Comment by leecher1337** [comment] 2018-05-24 10:56
It could be that there are no symbols on the Microsoft Symvol Server for updated system DLLs which are needed by the loader to do the injection.
To diagnose the issue, try Process Explorer to check if ldntvdm.dll got injected into every process.
If ldntvdm.dll was injected properly, use Sysinternals DbgView to check for log messages of the loader.
It should tell you, if for instance symbols cannot be resolved on Microsoft Symbol server.
If ldntvdm.dll was not injected properly, there may be an issues with your AppInitDLLs.

If the problem are missing symbols, you may need to open a support ticket at Microsoft regarding missing debug symbols for certain system DLLs.

You can also check if this was caused by an update and try to roll back updates to the point where it was working fine.

**Comment by leecher1337** [comment] 2018-05-28 21:07
Seems like they removed or renamed some internal symbol in the version that you are using.
Normally, DbgView output should also show a line "SymEng_GetAddr" before this telling you which symbol it tries to resolve.

**Comment by Valsamon** [comment] 2018-05-28 22:30
Yes, of course, it is BaseCreateVDMEnvironment.

**Comment by leecher1337** [comment] 2018-05-31 16:55
I just verified with the latest Windows 10 version and it works flawlessly on my machine.
Maybe your symbols are damaged.
Try to delete %TEMP%\SymbolCache directory

**Comment by Valsamon** [comment] 2018-06-01 05:30
Deleting %TEMP%\SymbolCache solved the problem, thank you very much!

**Comment by bilditup1** [comment] 2018-06-14 05:17
Deleting the symbol cache didn't help me. Initially I found nothing in dbgview, but after reinstalling, these errors recurred a whole bunch:

>00000429	1:00:18 AM	[5940] RegOpenKey failed: 00000002	
00000430	1:00:18 AM	[5940] Hook_IAT_x64_IAT(75C10000, ntdll.dll, NtCreateUserProcess, 731826B0, 7318AE28)	
00000431	1:00:18 AM	[5940] LDNTVDM: BasepProcessInvalidImageReal = 00000000	
00000432	1:00:18 AM	[5940] LDNTVDM: BaseIsDosApplication = 00000000	
00000433	1:00:18 AM	[5940] Hook_IAT_x64_IAT(75C10000, ntdll.dll, CsrClientCallServer, 73181FB0, 73188008)	
00000434	1:00:18 AM	[5940] Hook_IAT_x64_IAT(75C10000, ntdll.dll, CsrAllocateMessagePointer, 731821B0, 00000000)	
00000435	1:00:18 AM	[5940] Hook_IAT_x64_IAT(01190000, KERNEL32.DLL, SetConsolePalette, 73182D60, 7318AE24)	
00000436	1:00:18 AM	[5940] Hooking failed.	
00000437	1:00:18 AM	[5940] Hook_IAT_x64_IAT(75C10000, ntdll.dll, NtQueryInformationProcess, 73182C20, 00000000)	
00000438	1:00:18 AM	[5940] Hook_IAT_x64_IAT(75BA0000, ntdll.dll, NtQueryInformationProcess, 73182C20, 00000000)		

This is on Win7x64. Last time I checked this was still working on Windows 10, fwiw.

**Comment by leecher1337** [comment] 2018-06-17 16:13
It seems that you found a bug that I introduced by removing CreateProcess hooks, as the symbol update never triggered anymore on Windows 7.
I now added it to the NtCreateUserProcessHook (as it cannot be exeuted in DllMain, as this would cause a hang).

Please replace your windows\system32\ldntvdm.dll with the new one from ntvdmpatch\release\ldntvdm\system32\6.1\ldntvdm.dll from this repository.
Alternatively you an also replace it in your setup package and reinstall.

Please report back if it helps. In my tests, it worked. 
Regards

**Comment by leecher1337** [comment] 2018-06-19 07:41
Thank you for testing!
I didn't update the SysWOW64 build, as the first process that gets run on the 64bit machine where the DLL gets injected (i.e. explorer.exe) is a 64bit process, so update would be triggered there anyway.
Also triggering it in SysWOW64 lib wouldn't generally hurt and on next build, it will be in there too, but as said, there are enought 64bit processes around that would trigger it. So in short, it was just lazyness ;-)

The general point of the SysWOW64 build is to also inject the loader into 32bit applications. If it wouldn't be there, you wouldn't be able to launch DOS apps from 32bit apps and normally, users still have lots of 32bit apps.

**Closed** 2020-02-28 22:27 UTC
