### ISSUE TITLE
Sound emulators don't work with NTVDM

### ISSUE THREAD

**Issue by WindowsNinetyTen** [leecher1337/ntvdmx64#40] opened 2019-07-11 17:18 UTC
After installing VDMSound and then trying to open a progam with that, I just get a "bad command or file name" message. Why is this?

And also, for SoundFX, I can't use it at all, because it's a "time-limited" evaluation version.

**Comment by leecher1337** [comment] 2019-07-11 20:52
Did you even read their homepage?
http://www.softsystem.co.uk/products/soundfx.htm

There is a .reg file that disables time limitation right on the download page.

**Comment by leecher1337** [comment] 2019-07-11 21:07
[sndfx420.zip](https://github.com/leecher1337/ntvdmx64/files/3383976/sndfx420.zip)
This version works fine here.

**Comment by HomerBender77** [comment] 2019-07-11 21:31
> Did you even read their homepage?
> http://www.softsystem.co.uk/products/soundfx.htm

Yes, I did read their homepage and tried to apply the fix. But I still got the "time-limited evaluation message" even after applying the notime.reg file to the registry.

**Comment by peter8777555** [comment] 2019-07-11 23:37
The Source Code sbvdd.c

/*
 * Start evaluation timeout
 */
extern void StartEvalTimeout( void)
  {
  static MMRESULT s_hTimer;

  TRACE( 9, ("StartEvalTimeout()\n"));

  if ( !s_hTimer)
    {
    DWORD dwTimeout;

    /* Start the evaluation timeout */
    dwTimeout = 3 * 60 * 1000;
    s_hTimer = timeSetEvent( dwTimeout, 1000, &EvalTimeout, 0, TIME_ONESHOT);
    if ( !s_hTimer)
      {
      TRACE( 0, ("!!! StartEvalTimeout() timeSetEvent failed\n"));
      /* Immediate timeout */
      EvalTimeout( 0, 0, 0, 0, 0);
      }
    else if ( ReadRegValue( "PSQR@+,<", REG_DWORD, sizeof( dwTimeout), &dwTimeout)
      && 0x19541009 == dwTimeout
    ) {
      timeKillEvent( s_hTimer);
      }
    }
  }

**Comment by leecher1337** [comment] 2019-07-12 00:11
Recompiled sbvdd.dll free build for you, this one should work out of the box (replace it in your SysWOW64 directory):
[sbvdd.zip](https://github.com/leecher1337/ntvdmx64/files/3384413/sbvdd.zip)

**Comment by leecher1337** [comment] 2019-07-12 00:15
Btw: Reg-file probably doesn't work because it must go to WOW64 node on 64bit machines (NTVDM is 32bit application):

[notime.zip](https://github.com/leecher1337/ntvdmx64/files/3384420/notime.zip)

**Comment by peter8777555** [comment] 2019-07-12 00:43
sbvdd.zip WORK.
notime.zip Failed.

**Comment by HomerBender77** [comment] 2019-07-12 02:21
The sbvdd file worked and the problem is now gone. Thanks for your help!

**Comment by peter8777555** [comment] 2019-07-12 18:59
It seem do NOT support Ad Lib ??

**Comment by leecher1337** [comment] 2019-07-13 04:10
Which application did you try with? Also did you set FM Synthesis to emulation,because most PCI hardware soundcards don't prvide AdLib support.

**Comment by peter8777555** [comment] 2019-07-14 19:27
Please refer to the Sample.zip for more details.

SnapShot01.png
SnapShot02.png
SnapShot03.png
SnapShot04.png
SnapShot05.png
SnapShot06_IBM_PC_Sound_OK.png

[Sample.zip](https://github.com/leecher1337/ntvdmx64/files/3390361/Sample.zip)

**Comment by leecher1337** [comment] 2019-08-08 15:48
I found out that there are some weird issues with SoundFX and NTVDMx64. If it is enabled, some applications tend to hang on startup sometimes. As soon as SoundFX is disabled, applications work fine again. Not sure, if this is a bug in SoundFX2000 or NTVDMx64.

**Comment by AbdullahTrees** [comment] 2020-05-02 00:50
> I found out that there are some weird issues with SoundFX and NTVDMx64. If it is enabled, some applications tend to hang on startup sometimes. As soon as SoundFX is disabled, applications work fine again. Not sure, if this is a bug in SoundFX2000 or NTVDMx64.

It's been some months... Have you been able to figure out where the bug is?

**Comment by leecher1337** [comment] 2020-05-02 07:11
Has been fixed in https://github.com/leecher1337/ntvdmx64/commit/13fa209a548e0af064655759b60deff8d6b5c90e

Uninstall SoundFX2000 and just use NTVDMx64, as it now incorporates Adlib Mousic and Soundblaster Sound emulation in core.

**Comment by AbdullahTrees** [comment] 2020-05-06 19:48
> Uninstall SoundFX2000 and just use NTVDMx64, as it now incorporates Adlib Mousic and Soundblaster Sound emulation in core.

Awesome that explains why my Mavis Typing Tutor (uses only PC speaker) was making sound in Windows 10, I initially expected it to be totally quiet.
Btw, if you are incorporating SoundFX2000 into NTVDMx64, how do I change sound settings on DOS applications so that sound will work? (Basically asking for the IRQ number, channel, etc...)

**Comment by leecher1337** [comment] 2020-05-06 23:09
If your application only supports PC speaker and no Soundcard, you may want to install the PC Speaker driver mentioned in NTVDMx64 FAQ, as Windows 7 and higher ruined PC speaker output by replacing it with a totally unusable sine wave generator that doesn't abide timing constraints for output (the mentioned driver replaces BEEP.SYS and restores Windows XP behaviour that usese the real PC Speaker hardware. Of course,a PC Speaker needs to be connected to your mainboard in order to work).

Regarding Soundcard settings, see the BLASTER= variable in autoexec.nt
For music playback, Adlib Soundcard must be chosen, for Sound effects device, SoundBlaster (2.0). 
Most DOS applications obey the setting of the BLASTER environment variable. In most cases, it worked out of the box for me.

**Comment by leecher1337** [comment] 2022-01-07 22:18
Assuming Soundblaster support works for you via BLASTER= environment variable as described.

**Closed by leecher1337** 2022-01-07 22:18 UTC
