### ISSUE TITLE
Abnormal program termination: Invalid TSS fault

### ISSUE THREAD

**Issue by eguerrerojr** [leecher1337/ntvdmx64#147] opened 2021-08-19 06:17 UTC
Tried playing with this old program and this error occurs. Is there a workaround to this?

![error](https://user-images.githubusercontent.com/74942638/130017514-381d6499-b08b-4831-9bf1-02a98e1d23ae.png)

**Comment by leecher1337** [comment] 2021-09-02 07:08
Hi, do you have a download link for this program or can you attach it to the ticket? 
It may become handy to also analyze the crash in #138 , as this looks somewhat similar, but maybe easier to reproduce.

**Comment by junedgard** [comment] 2021-09-06 01:48
Good day sir. I will analyze and test crash #138 first, maybe it will resolve this issue. I will attach a copy of the program if the issue is still not resolved. Thanks.

**Comment by junedgard** [comment] 2021-09-07 01:18
The issue was resolved by replacing the ldntvdm.dll as what you have instructed on crash #28. Thank you for extending your help sir.

**Closed** 2022-02-09 02:56 UTC
