### ISSUE TITLE
Python and ntvdmx64: not valid application

### ISSUE THREAD

**Issue by padremayi** [leecher1337/ntvdmx64#180] opened 2022-03-17 11:31 UTC
Hi, I build the source code and from command line I can launch 16 bit applications without problems.

I'm working on a Python application and the problem is if I launch 16 bit app within Python it doesn't work. It seems that using os.system(), subprocess and other Python libraries, ntvdmx64 is not "intercepted". I receive the error that the application is not a valid application for current OS, like ntvdmx64 is not present.

Any idea?

**Comment by leecher1337** [comment] 2022-03-17 12:31
Have you checked with DbgView, if loader injects into your python runtime environment properly?  Maybe there is a problem with loader propagation into your process.

**Comment by padremayi** [comment] 2022-03-17 13:43
This is the output launching the app from command line:
[https://pastebin.com/4um9JHM8](url)

This is the one from Python:
[https://pastebin.com/KC7RF5wC](url)

**Comment by leecher1337** [comment] 2022-03-17 17:12
I don't see that it's running inside python.exe. When you launch your application, do you usually launch python.exe with the script file as a parameter?

Also try the following: Don't launch python <script> from cmd.exe commandline, but from Start/Run (press WIN+R), does it work from there? If so, then injection from console applications may not work.

**Comment by padremayi** [comment] 2022-03-17 17:38
Sorry, running from PyCharm, a Python IDE. This is the error if I launch with
`python script.py`

from command line:
`OSError: [WinError 87]`

The script is this:
```
import os
import subprocess


with open(os.path.join("TEST", "test.log"), "w", encoding="utf-8") as output_file:
    subprocess.call([os.path.join("TEST", "MYAPP.EXE")], stdout=output_file)
```

This is the output from DebugView:
[https://pastebin.com/KRdJNrFq](https://pastebin.com/KRdJNrFq)

**Comment by leecher1337** [comment] 2022-03-20 03:51
Please note that your code won't run on Windows 7 x86 with the real NTVDM either (I checked it).
This is due to the fact that CreateProcess parameter `bInheritHandles` is TRUE. 
So this is clearly *not* a bug, but works as intended.

I suggest you redesign your code.  In order to get thsi working, you can i.e. try with `CMD /C`:

`subprocess.call(["CMD.EXE","/C","MEM.EXE"], stdout=output_file)`

Closing this as it's not a bug.

**Closed by leecher1337** 2022-03-20 03:51 UTC

**Comment by padremayi** [comment] 2022-03-20 07:07
> subprocess.call(["CMD.EXE","/C","MEM.EXE"], stdout=output_file)

Open again only for report that it doesn't work. So if someone want to use this inside Python application it is not possible. Thanks

**Comment by leecher1337** [comment] 2022-03-20 10:37
Which Windows version did you try it on?
I tried it on Windows 8 x6 and Windows 11 x64, in both versions, it worked flawlessly:

test1.py:
```
import os
import subprocess


with open(os.path.join("TEST", "test.log"), "w", encoding="utf-8") as output_file:
    subprocess.call(["CMD","/C","MEM.EXE"], stdout=output_file)
```
after running that script, MEM.EXE output is in TEST\test.log

**Comment by padremayi** [comment] 2022-03-20 11:50
Windows 10 x64, after running the script the file test.log is blank.

Maybe the problem is the 16 bit application that I have to use, but presented method doesn't ALWAYS works. Running the same application with the same parameters from command line works without any problem.

Appreciate your help, changed code flow to DOSBox and .bat file executed from it

**Comment by leecher1337** [comment] 2022-03-20 12:15
One thing that comes to my mind is the injection technique used with the pre-Win11 loaders that can indeed lead to situations where the injection into a command line process isn't done early enough and so the application doesn't always load LDNTVDM just in time to redirect output to NTVDM.EXE

The Windows 11 loaders also work on Windows 10, if you are interested, you can swap Win10 loader with Win 11 loader DLLs and check if it helps.
To try it out, uninstall ntvdmx64, modify install.bat and before the line 
`set ORIGVERSION=%VERSION%`
insert the line
`set VERSION=11.0`

**Comment by padremayi** [comment] 2022-03-20 14:24
I confirmed that with a Python script like this one:
```
import os
import subprocess


with open(os.path.join("TEST_FOLDER", "test.log"), "w", encoding="utf-8") as output_file:
    subprocess.call(["CMD.EXE", "/C", os.path.join("TEST_FOLDER", "APP.EXE"), "-test_parameter"], stdout=output_file)
```
with **ntvdmx64** installed on **Windows 10** x64 with install.bat (from _releases/language_ folder) modified adding this line:
`set VERSION=11.0`
before this one:
`set ORIGVERSION=%VERSION%`
works like a charm.

So the problem was the Windows 10 loader "loading time". Really appreciate, thanks
