### ISSUE TITLE
Source of old-src.trunk.r687.20150728.7z and MinNT-20170416-85fac4faadc77203db8ddc66af280a75c1b717b0.zip

### ISSUE THREAD

**Issue by GitJJHub** [leecher1337/ntvdmx64#221] opened 2023-03-28 22:18 UTC
Using Google and Wayback searches, I can't find a source for either of these required files:
old-src.trunk.r687.20150728.7z 
MinNT-20170416-85fac4faadc77203db8ddc66af280a75c1b717b0.zip

Help please.
Thanks,
Jerry

**Comment by leecher1337** [comment] 2023-03-29 06:54
Duplicate of https://github.com/leecher1337/ntvdmx64/issues/212

**Closed by leecher1337** 2023-03-29 06:54 UTC
